### PR TITLE
Testcases for french avenues

### PR DESCRIPTION
**Pull request by chatelao**

### CODE REVIEW

**Comment by giggls** [comment]
Please add test cases fpr english as well.

**Comment by giggls** [comment]
* 5th Avenue
* 1st Avenue
* 2nd Avenue

In best case those should match, but french versions should not.

**Comment by chatelao** [comment]
Should be included

**Comment by giggls** [comment]
OK, tests look fine. Should I merge this or do you want to write the actual code first?

**Comment by chatelao** [comment]
You can meege it, I think your Code is already close to target.

**Comment by giggls** [comment]
OK, will put this into a single commit together with my changes.

**Comment by chatelao** [comment]
Perfect, thank you

**Pull request closed without merging**
