### PR TITLE
More Avenue logic (en) and micro fix (fr)

### PR DESCRIPTION
**Pull request by chatelao**
- Micro fix ^^ as ^
- Normalize "1([eè]?r?)e Avenue to "1re Avenue"
- Use RegExp for EN too

### CODE REVIEW

**Comment by giggls** [comment]
it does not make a lot of sense to link to an URL which produces an error:
https://regex101.com/r/bYk8ki/2
does not work for me:
"? The preceding token is not quantifiable"

**Comment by chatelao** [comment]
Ups, I didn't know it is private - Does this one work? https://regex101.com/library/Tiyneo

**Comment by giggls** [comment]
Same error. For me this looks like the portal does not understand this type of regular expression:
error

**Comment by chatelao** [comment]
Strange, the original was set to the second mode and worked fine. Maybe this is a local preference to each user.

**Comment by giggls** [comment]
Just remove the URL references, I will merge and close it then.

**Comment by chatelao** [comment]
The xomments are removed.

Die you know about this service for PostGre snippets?j
- https://dbfiddle.uk/?rdbms=postgres_10&fiddle=4607fadafe560e8c8aa7e62c5ed4c842

Maybe the next time I will provide the samples over there.

**Comment by giggls** [comment]
As Web services do not tend to be very long lasting. I think its better to not clutter source code with links which may no longer work anyway.

**Pull request merged**
