### PR TITLE
Split osml10n_street_abbrev_all in function of the detected alphabet to overpass the limit of cached regex #40

### PR DESCRIPTION
**Pull request by frodrigo**
Use less regex by using latin or not sub function.

Avoid regex cache limit.

Less regex -> beter perf.

### CODE REVIEW

**Comment by giggls** [comment]
Hm wouldnt it be better to implement this like osml10n_contains_cjk function and not even use a regular expression at all?

**Comment by frodrigo** [comment]
Yes. I think about.

**Comment by giggls** [comment]
I think we should add a osml10n_contains_cyrillic function.

**Comment by frodrigo** [comment]
Done, but it is not working.

Even EN + FR have too much regex.

**Comment by frodrigo** [comment]
Update with really less regex.

* Split osml10n_street_abbrev_all in function of the detected alphabet to overpass the limit of cached regex
* Rewrite osml10n_street_abbrev_fr and osml10n_street_abbrev_en to use less regex
* Remove regex from osml10n_street_abbrev_ru and osml10n_street_abbrev_uk

**Comment by giggls** [comment]
Does this recover original speed?

**Comment by frodrigo** [comment]
Ho yes forgot the benchmark.

Applying on all highway of Luxembourg take 2min20s with the current implementation.
With this change takes 2s. I think it it better than original (4s I guess).

**Comment by giggls** [comment]
Hm should have been tried to build this before merging.

I get the following errorfrom automated build after calling
``CREATE EXTENSION osml10n CASCADE;``

```
ERROR:  function osml10n_street_abbrev_non_latin(text) does not exist
LINE 4:     osml10n_street_abbrev_non_latin(longname)
                ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
```

**Comment by frodrigo** [comment]
I will look at this tomorrow. But I does not change the signature. Many be there is an other error before this one.

**Comment by giggls** [comment]
Likely a problem of the order the functions are created. This would also explain why you did not see it while developing your code.

**Comment by giggls** [comment]
Found the problem. Definitely my fault. My bash script was broken, I need to fix this.

**Comment by giggls** [comment]
Can you please check why test fails on "Boulevard de Pérolles" now?

**Pull request merged**
