### PR TITLE
Add - Minimalistic NL abbreviations

### PR DESCRIPTION
**Pull request by chatelao**
According to the 80/20 the "straats" (and saints) for Amsterdam.

### CODE REVIEW

**Comment by giggls** [comment]
I will likely not merge this. 
I had some discussion about this topic with a dutch guy back at FOSS4G. Unfortunately I do not remember correctly anymore why this is the case, but he told me about doing dutch street-name abbreviations being somewhat complicated.

So as this would be of minimal value anyway I would only accept this from a native speaker before doing something wrong.

I thought I already made this clear in the other issue:
"Please do not try to implement further strange features like this out of the blue."

Are you really looking for something to help at this particular code and if so why is this?

Looks like I have to add a TODO file though.

**Comment by giggls** [comment]
https://github.com/giggls/mapnik-german-l10n/commit/6e963984c8b437dde1199fb408ef9aa779de3a82

**Comment by chatelao** [comment]
I'll check this with some durch guys. I really consider the abbreviations an enhancement of maps, as it increases the densitiy of the information available lower resolution. Therefore I check out how to push the topic forward.

If you think, even this radical minimalistic rule adds no value - that's fine, I will continue to work in your code base, as it is an nice start. But don't expect me to create any pull requests in the close future, sorry.

**Comment by giggls** [comment]
I think I already wrote this. The sole reason for adding streetname abbreviation functions to this repository was the fact, that dual-language names in non-latin script + latin-script tend to get very long. So this was the reason I added them for Russian and English in the first place.

While there are at least places where this is relevant for french also I took your last patch.

As I know of no place where dutch street-names come in bilingual flavour I do not consider this an important task for this language.

This is about l10n here and not about abbreviations here after all.

**Comment by chatelao** [comment]
It's very good, that you clarify the L10n focus. I enjoyed the readability on www.openstreetmap.de due to the density and the focus of the abbreviations (see the sample below):

| Long names | Short names |
| --- | --- |
| Long| Short names |

Due to this "aha effect" I want to try to improve the wordwide quality of abbreviations available. If this is not your focus it is really the better idea to split the features and maybe if the I get the quality to a point you think it is good enough and useful for you, a merge will make sense and I'll be more than happy to share the results.

**Comment by giggls** [comment]
I strongly feel, that name abreviation code should not be merged here but instead an external project should be set up which can then be and used in osml10n instead of the current code in
the long run.

You might want to have a location based approach in generation of abbreviations.
To achieve this goal you can use the table at:
http://wiki.openstreetmap.org/wiki/Nominatim/Country_Codes and my osml10n_get_country function.

This is currently not done here as I consider it too expensive doing spatial queries for the generation of every single name.

**Pull request closed without merging**
