### PR TITLE
Optimize SQL functions

### PR DESCRIPTION
**Pull request by nyurik**
* Use SQL instead of 'plpgsql' when possible (allows for inlining)
* declare functions as strict when relevant
* mark abbreviation functions as parallel safe
* add execution cost lower than the default 100 for non-data-accessing functions.
* trimmed a few trailing spaces

### CODE REVIEW

**Comment by giggls** [comment]
Can you please merge this with PR #42

**Comment by nyurik** [comment]
@giggls I applied #42 into this PR as https://github.com/giggls/mapnik-german-l10n/pull/43/commits/49b74b6ee6b7d577f2bf529cb524eeeae58b3322 , but note that many statements there were not parallel safe (see comment)

**Comment by giggls** [comment]
Honestly, I dont like these SQL replacements that much.

**Comment by nyurik** [comment]
@giggls which SQL replacements?  Are you talking about PGPSQL -> SQL replacements?  Take a look at https://github.com/giggls/mapnik-german-l10n/pull/47 -- shows the testing process and how much faster they run as SQL rather than PGPSQL. Try running it locally - you will see the performance differnec.

**Comment by giggls** [comment]
I have not been talking about osml10n_get_country but rather about your changes in street_abbrv.sql.

The major performance trouble we had there was with a hardcoded number of compiled regular expressions in PostgreSQL.

Do you really expect performace gains using these ugly ((( stuff?

BTW I think about abandoning this approach altogether because #35 is unresolvable because if performance issues using PL/Python.

Some thoughts about another approach are here:
https://github.com/giggls/osml10n

**Comment by nyurik** [comment]
@giggls If I change just a single `osml10n_street_abbrev_latin` from `plpgsql` to `sql` gains 3.8% performance.   I tried it by declaring both variants as `volatile` (so that I can pass the same hardcoded string to it multiple times), and when using a random string `substr(md5(random()::text), 0, 25)`. 

Note that the number is so low because there is considerable processing in sub-functions. When I apply all of the changes together (running existing code vs all the new functions), the gain is ~13%:
```
% slower    Function                                                AVG of 8 runs    MIN             MAX                 STDEV
----------  ------------------------------------------------------  ---------------  --------------  --------------  ---------
            2) new_osml10n_street_abbrev_latin(substr(md5(random(…  0:00:01.204847   0:00:01.193433  0:00:01.252285  0.019945
12.6%       1) old_osml10n_street_abbrev_latin(substr(md5(random(…  0:00:01.357166   0:00:01.344912  0:00:01.380302  0.0145648
```

**Comment by nyurik** [comment]
Thanks for the heads up about the issue #35 -- I'm all for making it even better and faster, but one thing at a time -- at the moment we have this implementation, so lets make it as fast as possible. Once the new implementation is ready, we will have a good baseline performance numbers to measure against.

**Comment by nyurik** [comment]
@giggls are there any blockers to merge this? I think a 15% performance improvement is worth a few extra parentethis, although I agree that ideally we should use something else if possible. This does not stop is from working on a better overall system. Thanks!

**Comment by giggls** [comment]
While I still think theses SQL function are somewhat incomprehensible I will merge this code for the sake of completeness. 

But as I already said I am afraid that this whole approach of using stored procedures will not be sustainable in the long term.

I strongly feel this should be done at import time.

We just fixed a major performance impact in ``street_abbrv.sql`` by a workaround reducing the number of regular expressions instead of a solution.

Furthermore closing #35 is likely impossible using the current approach.

**Comment by nyurik** [comment]
@giggls maybe this should be discussed in a different ticket, but could you clarify about the import time?  The [OpenMapTiles project](https://github.com/openmaptiles/openmaptiles) has just two stages -- the `imposm` stage (PBF->Postgres), and the tile generation stage (Mapnik at the moment, but moving towards pure Postgres `ST_AsMVT` approach). The update (from the by-minute source) uses similar pipeline. The MVT will be generated as a whole on the fly -- i.e. my future plan is to build a real-time server -- up to minute data, generating tiles on demand.   What stage do you see the string manipulations applied?

**Comment by giggls** [comment]
ACK. I will open a new ticked regarding this issue.

**Comment by nyurik** [comment]
@giggls once again thanks for merging!  Could you do a new release with all the changes, or do you have something scheduled? Thx!

**Comment by giggls** [comment]
Yes, I think I will.

**Pull request merged**
