### PR TITLE
Fix nominatim curl

### PR DESCRIPTION
**Pull request by lazaa32**
Add -L option to curl command
Use https for nominatim url to country_grid.sql.gz

### CODE REVIEW

**Comment by otbutz** [comment]
Could you change the URL to https://nominatim.org/data/country_grid.sql.gz (without the www)? This way we can skip the `-L`

**Comment by otbutz** [comment]
@giggls could you publish a release with the fix?

**Comment by giggls** [comment]
Not without making CI build work again.

**Comment by otbutz** [comment]
Looks like `pg_config` detects a PG14 installation being present:

```
make[4]: Entering directory '/home/runner/work/mapnik-german-l10n/mapnik-german-l10n/src/kanjitranscript'
cc -fpic -fno-exceptions -I/usr/include/postgresql/14/server -c kanjitranscript.c
```

**Comment by giggls** [comment]
Frankly I don't care about Ubuntu that much because I don't use it myself. But currently this does not seem to build on Debian 11 (which I do use) also.

**Comment by giggls** [comment]
But why Postgresql 14? Regarding the documentation ubuntu-latest should be ubuntu-20.04 which comes with Postgresql 12 regarding https://packages.ubuntu.com/

**Comment by otbutz** [comment]
```
pg_config --version
which pg_config
```

**Comment by giggls** [comment]
I know, but there should be no PostgreSQL 14 on Ubuntu 20.04 but PostgreSQL 12.
I have no development machine where I could test with PostgreSQL 14.

**Comment by otbutz** [comment]
Github actions doesn't appear to be vanilla Ubuntu 20.04

https://github.com/actions/virtual-environments/blob/ubuntu20/20211122.1/images/linux/Ubuntu2004-README.md#databases

**Comment by giggls** [comment]
*argh* this is evil this way I can not even use a chroot and try to find the bug.

**Comment by otbutz** [comment]
Well you *could* uninstall all postgres versions and install your blessed version after that.

**Pull request merged**
