### PR TITLE
Implement Github Action CI workflow

### PR DESCRIPTION
**Pull request by nyurik**
Adapted .gitlab-ci.yml as a Github action workflow.

Automatically tests pull requests and commits.

### CODE REVIEW

**Comment by nyurik** [comment]
@giggls this could probably use your help -- I [got it to build](https://github.com/nyurik/mapnik-german-l10n/runs/676933440?check_suite_focus=true), but the testing phase breaks on missing `setuptools`?  I think it would be much better to do all the testing using postgis [docker images](https://registry.hub.docker.com/r/postgis/postgis/) (available for many different PG and Postgis versions)

```
Collecting tltk
  Downloading https://files.pythonhosted.org/packages/cd/87/fc57b0fb356222ae36fffaacf5f47ad9c38001d49695b42d4f21e03da844/tltk-1.3.5.tar.gz (11.3MB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ModuleNotFoundError: No module named 'setuptools'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-s3v0jq1n/tltk/
##[error]Process completed with exit code 1.
```

**Comment by giggls** [comment]
My code has never been tested on anything but Debian and Ubuntu. Which Linux distro are these docker images build on?

**Comment by giggls** [comment]
Sorry, did not see the ubuntu latest in your ci file. Looks like you need to install python3-setuptools.

**Comment by nyurik** [comment]
@giggls ah, silly me, fixed. Now the tests run, and there is one test that fails -- see [here](https://github.com/nyurik/mapnik-german-l10n/runs/696978359?check_suite_focus=true#step:6:682)

```
FAILED] (expected >Bd de Pérolles<, got ><)
select osml10n_get_streetname_from_tags('"name"=>"Chemin des bains"' false);
```

Is that something that should be fixed? BTW, if you are ok with this change, please merge it as is so that we can see the test results already.  Note that you may need to enable GitHub actions (workflows) on your repo.

**Comment by giggls** [comment]
Did this include my current commit?
I think I fixed exactly this just an hour ago. Was caused by the pull request I took from @frodrigo

**Comment by nyurik** [comment]
I just rebased and squashed it, works!  https://github.com/nyurik/mapnik-german-l10n/runs/697086492?check_suite_focus=true

**Pull request merged**
