### PR TITLE
Add - Vagrantfile Debian for Continous integrations

### PR DESCRIPTION
**Pull request by chatelao**
Provide a one-stop build environment for developers & testers

### CODE REVIEW

**Comment by giggls** [comment]
Sorry, that I need to say this, but I have the strong impression, that you are doing a whole lot of work here for stuff which is only slightly useful in this case and does not help that much.

While I still think, that CI is not necessary in this project at all I just tried it myself using gitlab-ci (which I did because I already know how to use it) and here is all I needed to do. This is just using the official docker Debian 10 image.

```yaml
# * build postgresql-*-osml10n_*_amd64.deb
# * run tests for the osml10n and osml10n_thai_transcript
image: debian:10

variables:
  LANG: C.UTF-8

build:
  stage: build
  before_script:
     - apt-get update
     - apt-get -y install devscripts equivs
     - mk-build-deps -t "apt-get -y" -i debian/control
  script: 
    - make deb
    - mkdir build
    - mv ../*.deb ../*.buildinfo ../*.changes build
  artifacts:
    paths:
      - build/*

# run tests using the binary built before
test:
  stage: test
  before_script:
     - apt-get update
     - apt-get -y install postgresql postgis postgresql-plpython3 
     - apt-get -y install python3-pip python3-matplotlib
     - apt-get -y install libkakasi2 libutf8proc2 icu-devtools
     - pip3 install tltk
     - dpkg -i build/postgresql-*-osml10n_*_amd64.deb
  script:
    - ./tests/runtests_in_virtualenv.sh
```

There are two things I do not like n your script:

1. It seems to double stuff fom `runtests_in_virtualenv.sh` 
2. It seem to have a dependency on PostgreSQL 11.

I would strongly suggest using `runtests_in_virtualenv.sh` instead of `runtests.sh` and getting rid of the PostgreSQL 11 dependency in the way my `.gitlab-ci.yml` does.

**Comment by giggls** [comment]
One more thing, I just found this and tend to use them instead of external services.
https://www.heise.de/newsticker/meldung/GitHub-baut-CI-CD-Funktionen-aus-4490917.html

**Comment by chatelao** [comment]
Thank you a lot for the link, I already signed up for the beta 😊

**Comment by giggls** [comment]
I will suspend this CI stuff until github releases its system.

**Comment by chatelao** [comment]
That's perfectly fine for me - I will get it running for Vagrant (locally for development) and GitHub-Actions for CI. Currently watching a video about the Github Actions: https://www.youtube.com/watch?v=E1OunoCyuhY

**Comment by chatelao** [comment]
Let's close it and reopen after the GitHub-Actions launch.

**Pull request closed without merging**
