### PR TITLE
More french and english street abbreviations

### PR DESCRIPTION
**Pull request by chatelao**
More French (Based on #22 and personal contacts) and English street abbreviations, including more tests (based on .csv test data) and documentation describing the rules and linking to real map tiles.

Here is the testlog without the new TH-Libs:
- https://travis-ci.com/chatelao/mapnik-german-l10n/builds/132433641

n.b.: All tests run well without the new Thai changes, which I couldn't get up & running. But I bet, this will not be an issue for @giggls as his environment is in better shape.

### CODE REVIEW

**Comment by giggls** [comment]
Mostly fine, but I have two things:
1. I do not want to have street_abbreviations.md in this repository. The external reference in street_abbrv.sql like I have it in English is enough
2. I do like the idea to have test results in external files, but if we do this in English and French we should also do this in in the other supported languages (de, ru and uk) for the sake of consistency.

**Comment by chatelao** [comment]
Thanks for the feedback:
1. I like to keep some Kind of human readable specification. Probably extendig the csv will be an Option and removing all non-implemented Cases.
2. I'm not sure how well it will work with non-ASCII Texts, it already struggled with single quotes.

**Comment by giggls** [comment]
1. Nack, please do not clutter this repo with only slightly related documentation. A hyperlink is definitely enough. We can put this into the wiki of this repo if you like.
2. There is no need to quote UTF-8 characters. As far as shell is concerned, there is no difference between something like ` ê, д or น`

**Comment by giggls** [comment]
1. Nack, please do not clutter this repo with only slightly related documentation. A hyperlink is definitely enough. We can put this into the wiki of this repo if you like.
2. There is no need to quote UTF-8 characters. As far as shell is concerned, there is no difference between something like ` ê, д or น`

As far as 2. is concerned I can also do this myself and merge your code before.

**Comment by chatelao** [comment]
1. The documentation is removed now.
2. If you could integrate the Cyrillic cases would be great.

**Pull request merged**
