### PR TITLE
Added street suffixes abbreviations for Ukrainian

### PR DESCRIPTION
**Pull request by Edward17**

### CODE REVIEW

**Comment by giggls** [comment]
Cool. Could you please also add an usage example in the comment as with
`select osml10n_get_streetname('улица Воздвиженка',NULL,NULL,NULL,true,'de')`
for russian?

**Comment by Edward17** [comment]
@giggls do you mean e. g.
```
select osml10n_get_streetname('вулиця Молока',NULL,NULL,NULL,true,'de');
       --> "вул. Молока (vul. Moloka)"
```
?

**Comment by giggls** [comment]
Yes, seems to work:

```
sven=> select osml10n_get_streetname('вулиця Молока',NULL,NULL,NULL,true,'de');
  osml10n_get_streetname   
---------------------------
 вул. Молока (vul. Moloka)
(1 Zeile)
```

**Comment by Edward17** [comment]
@giggls added.

**Pull request merged**
