### PR TITLE
Travis Continous Integration

### PR DESCRIPTION
**Pull request by chatelao**
Konfiguration für das automatische Testen auf "Travis CI"

### CODE REVIEW

**Comment by giggls** [comment]
Did you somehow resolve the chicken and egg problem, that **make test** will not run without prior installation of this extension itself? And how did you solve the thai language stuff?
I rather doubt that I will currently need some CI stuff, as this is a one-man show anyway and I usually run make test manually before pushing changes.

**Comment by chatelao** [comment]
Hallo Sven, das ist genau das schöne an der Sache:
- Die Integration compiliert und installiert die Erweiterung.für jeden Commit und jede Pull-Request automatisch, sprich: es liegt für jede Version ein Prüfportokoll vor.
- Sobald der Commit auf GitHub eintrifft, wird die Kette ausgelöst, hier das Beispiel zum aktuellen Stand: https://travis-ci.com/chatelao/mapnik-german-l10n/jobs/245749609

Gebaut und installiert wird sie durch die .travis.yml
- https://github.com/chatelao/mapnik-german-l10n/blob/travis-ci/.travis.yml

Der letzte Abschnitt "script" für den Test durch.

Was das "Thai" betrifft, ja da wird noch ein Fehler geworfen. Allerdings spreche ich kein Thai und kann nicht beurteilen, ob der Code oder die Tests falsch sind. - Vielleicht hast Du mir etwas Hintergrundwissen dazu.

Für die geplanten Anpassungen in Französisch bin ich sehr zuversichtlich, so recht gut wiederholbare Testfälle zu schreiben zu können.

**Comment by giggls** [comment]
Lets keep this in English. I don't speak Thai as well, but I can clearly see if a transcription is useful which will be enough in this case.

As far as CI is concerned I am still not convinced, that this is really needed in this project. This said I am willing to merge this, but I have two comments:

1. My main development platform is Debian stable so running CI on Ubuntu does not make sense for me.
2. Thai language support has to be tested as well.

I will thus postpone this until I have got issue #20 fixed. Stefan does speak Thai.

**Comment by chatelao** [comment]
Okay, looks better now:
- https://travis-ci.com/chatelao/mapnik-german-l10n/builds/132033823

The Thai question:
- The Thai tests run now green as well (The associated phyton modules missed)

The Debian/Ubuntu question:
- Unfortuntly, travis-ci doesn't support debian
- The Ubuntu distro is a Debian fork: https://www.ubuntupit.com/debian-vs-ubuntu-top-15-things-to-know-before-choosing-the-best-one/
- In mid term I could migrate all installation step to distro-independent scripts and add a Debian Vagrant Box to develop - But up to now the setup was already a pain (mainly due to my lack of knowledge) and runs as expected for the current scope.

**Comment by giggls** [comment]
Strange beast. The CI-systems I know about (gitlab-ci, jenkins) can all be run in a way, that they start from an arbitrary docker image.
So where should I go with this from here? Frankly, I don't know.

As I already said, I do not feel the need for using a CI system in this case at all, as the number of contributors to this Software is very low at best, basically mostly a one man show.

As things are with you code, I will still need to manually run my tests on Debian as the critical stuff are likely some subtle differences between Debian and Ubuntu :(

BTW, did yo try to build current head?

**Comment by chatelao** [comment]
Sorry, I checked the current "master" and didn't get it running (yet), maybe I missed a (new) dependency. - I will investigate further and see how to fix this.

**Comment by giggls** [comment]
The difference is actually `pip3 install tltk` instead of `pip3 install pythainlp` and for some strange reason tltk will run only with python3-matplotlib installed even if this is not used in my python code.
Maybe I should use `from tltk import nlp` instead of plain `import tltk`.

**Comment by chatelao** [comment]
Closed for new solution from GitHub coming in November.

**Pull request closed without merging**
